
#
@server = http://localhost:3000

###
GET {{server}}/person

###
POST {{server}}/person
Content-Type : application/json
{
    "name" : "Andy",
    "age" : 30,
    "email" : "andy@backend.com"
}

###
GET {{server}}/person/andy@backend.com 

###
PUT {{server}}/person/andy@backend.com 
Content-Type : application/json
{
    "age" : 24
}

// ###
// DELTETE {{server}}/person/andy@backend.com